DEMO_STATE = {
    "brand_name": "Unigo Footwear",
    "skus": [
        {
            "sku_id": "SKU-003",
            "name": "Velar Runner",
            "inventory_left": 180,
            "daily_velocity": 32,
            "reorder_threshold": 240,
            "projected_stockout_days": 5.6,
            "contribution_margin_after_rto": 28,
            "spend_growth_percent": 22,
            "campaigns": ["Velar-Static-V1"],
        }
    ],
    "campaigns": [
        {
            "campaign_id": "cmp_t2_cod_may",
            "campaign_name": "Tier2-COD-Lookalike-May",
            "spend": 18400,
            "spend_growth_percent": 16,
            "roas_on_placed_orders": 3.8,
            "roas_on_delivered_orders": 2.1,
            "frequency": 3.2,
            "ctr_drop_percent": 8,
            "cod_order_count": 186,
            "cod_ratio": 67,
            "rto_count_attributed": 58,
            "delivered_orders_attributed": 187,
            "rto_rate_attributed": 31,
            "contribution_margin_after_rto": 8,
            "skus": ["Velar Runner"],
        },
        {
            "campaign_id": "cmp_velar_static_v1",
            "campaign_name": "Velar-Static-V1",
            "spend": 9400,
            "spend_growth_percent": 22,
            "roas_on_placed_orders": 3.2,
            "roas_on_delivered_orders": 2.7,
            "frequency": 5.4,
            "ctr_drop_percent": 34,
            "cod_order_count": 41,
            "cod_ratio": 45,
            "rto_count_attributed": 11,
            "delivered_orders_attributed": 93,
            "rto_rate_attributed": 11.8,
            "contribution_margin_after_rto": 24,
            "skus": ["Velar Runner"],
        },
    ],
    "customer_segments": [],
}
